---
- name: collect all files with suffix conf
  become: yes
  find:
    paths: /etc/icinga2/features-enabled
    patterns: '*.conf'
    file_type: any
  register: collected_features
  when: icinga2_purge_features

- name: collect enabled features
  set_fact:
    features_enabled: "{{ features_enabled|default([]) + [ item.path| basename| splitext | first ] }}"
  loop: "{{ collected_features.files }}"
  when: icinga2_purge_features

- name: purge features
  become: yes
  file:
    state: absent
    path: "{{ '/etc/icinga2/features-enabled/' + item + '.conf' }}"
  loop: "{{ features_enabled| difference(icinga2_features| map(attribute='name')) }}"
  notify: reload icinga2 service
  when: icinga2_purge_features

- name: configure features
  become: yes
  template:
    src: templates/feature.conf.j2
    dest: "{{ '/etc/icinga2/features-available/' + item.name + '.conf' }}"
  loop: "{{ icinga2_features }}"
  when: item.state is undefined or item.state != 'absent'
  notify: reload icinga2 service

- name: manage features
  become: yes
  file:
    state: "{{ 'link' if (item.state is undefined or item.state != 'absent') else 'absent' }}"
    path: "{{ '/etc/icinga2/features-enabled/' + item.name + '.conf' }}"
    src: "{{ '../features-available/' + item.name + '.conf' if (item.state is undefined or item.state != 'absent') else omit }}"
  loop: "{{ icinga2_features }}"
  notify: reload icinga2 service
