---
- name: Include OS specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'
- name: add icinga repositories
  include_role:
    name: icinga_repo
  when: icinga2_manage_repos

- name: install icinga2
  include: "install_on_{{ ansible_os_family }}.yml"

- name: configure icinga2
  include: configure.yml

- name: manage service icinga2
  include: service.yml
